# Numpy

* NumPy is Known as Numerical Python.
* Numpy is a foundamental library for working with arrays and mathematical operations in Python. It is commonly used for data analysis,scientific computation, and machine learning.
* It serves as the foundation for many data science and scientific computing libraries, including Pandas, SciPy, Scikit-Learn, and TensorFlow, due to its performance and flexibility.
*  NumPy allows for efficient operations on data in Python.
*  Vectorized Computations.

#### Import numpy library

In [114]:
import numpy as np

In [115]:
## Creating array
arr=np.array([7,5,4,3,9])
arr

array([7, 5, 4, 3, 9])

In [116]:
# Data type
arr.dtype

dtype('int32')

In [117]:
arr.ndim

1

In [118]:
arr.shape

(5,)

In [119]:
## arange() returns a new lits with evenly spaced values in given range.
list=np.arange(1,10)
list

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
## linspace() returns a new lits with evenly spaced values in given range.
list=np.linspace(1,10,5)
list

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Difference Between linspace() aand arange() :
* linspace() include stop value by default, while arange() excludes it.
* linspace() allows specifying the number of samples,while arange() requires specifying the step  size.

In [121]:
## logspace() returns evenly spaced log values.
list1=np.logspace(1,10,5)
list1

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [122]:
## To change datatype of an array we have function called astype()
arr.astype(np.float64)

array([7., 5., 4., 3., 9.])

In [123]:
## Indexing and slicing
arr[1:]

array([5, 4, 3, 9])

In [124]:
## Creating 2D array
num=np.array([[1,2,3],[4,5,6],[6,7,8]])
num

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [125]:
num.shape

(3, 3)

In [126]:
## Creating 3D array
num1=np.array([[[1,2,3],[3,4,5]],[[2,3,4],[7,8,9]]])
num1

array([[[1, 2, 3],
        [3, 4, 5]],

       [[2, 3, 4],
        [7, 8, 9]]])

In [127]:
num1.shape

(2, 2, 3)

### Basic Element Wise Operation:
> Basic element operations in NumPy involve performing arithmetic and mathematical operations directly on NumPy arrays. These operations are typically element-wise, meaning they operate on corresponding elements of the arrays.

In [128]:
arr1=np.array([3,4,7,8])
arr2=np.array([2,9,1,4])

In [129]:
## Addition
arr1+arr2

array([ 5, 13,  8, 12])

In [130]:
## Subtarction
arr1-arr2

array([ 1, -5,  6,  4])

In [131]:
## Multiplication
arr1*arr2

array([ 6, 36,  7, 32])

In [132]:
## Division 
arr1/arr2

array([1.5       , 0.44444444, 7.        , 2.        ])

In [133]:
## Modular
arr1%arr2

array([1, 4, 0, 0])

In [134]:
## Square root
np.sqrt(arr1)

array([1.73205081, 2.        , 2.64575131, 2.82842712])

In [135]:
## Exponential
np.exp(arr2)

array([7.38905610e+00, 8.10308393e+03, 2.71828183e+00, 5.45981500e+01])

### Manipulation of Data:
> Manipulating data using NumPy involves a wide range of operations that allow you to reshape, index, slice, join, split, and modify arrays. These manipulations are essential for preparing data for analysis, cleaning, and transforming datasets in a way that allows for more effective computation.

In [136]:
# Reshaping
arr=np.array([1,2,3,4,5,6,7,8,9])
a=arr.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
# Transpose
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [139]:
# Conatenation
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6]])
concatenated = np.concatenate((arr3, arr4), axis=0)
print("Concatenated along rows:\n", concatenated)
concatenated_cols = np.concatenate((arr3, arr4.T), axis=1)
print("Concatenated along columns:\n", concatenated_cols)

Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]]
Concatenated along columns:
 [[1 2 5]
 [3 4 6]]


In [140]:
# Adding element to a array
arr5 = np.array([1, 2, 3])
print(f"Appended array: {np.append(arr5, [4, 5])}")

Appended array: [1 2 3 4 5]


In [141]:
# Insert elements at specific positions
print(f"Array after insertion: {np.insert(arr5,1,[10,20])}")

Array after insertion: [ 1 10 20  2  3]


In [142]:
# Delete elements from an array
print(f"Array after deletion: {np.delete(arr5,[1])}")

Array after deletion: [1 3]


In [143]:
# Unique elements
num=np.array([2,2,3,9,8,8,3,5,2])
np.unique(num)

array([2, 3, 5, 8, 9])

### Aggregation of Data:
> Aggregating data using NumPy involves performing various operations that summarize information from arrays. These operations include calculating sums, means, medians, variances, and other statistical measures. Aggregation functions in NumPy are optimized for performance and can handle large datasets efficiently.

In [144]:
arr=np.array([[1, 2, 3], [4, 5, 6]])

In [145]:
# Sum of all elements
print(f"Total Sum: {np.sum(arr)}")
# Sum along rows (axis 0)
print("Sum along rows:",np.sum(arr, axis=0) )
# Sum along columns (axis 1)
print("Sum along:",np.sum(arr, axis=1))

Total Sum: 21
Sum along rows: [5 7 9]
Sum along: [ 6 15]


In [146]:
# Mean
print("Mean:",np.mean(arr))

Mean: 3.5


In [147]:
# Median
print("Median:",np.median(arr))

Median: 3.5


In [148]:
# Standard Deviation
print("Standara deviation:",np.std(arr))

Standara deviation: 1.707825127659933


In [149]:
# Varience
print("Variance:",np.var(arr))

Variance: 2.9166666666666665


In [150]:
# Minimum
print("Minimum:",np.min(arr))

Minimum: 1


In [151]:
# Maximum
print("Maximum:",np.max(arr))

Maximum: 6


In [152]:
# 25th Percentile
np.percentile(arr,25)

2.25

### Analysing of Data:
> Analyzing data using NumPy involves using its powerful array manipulation capabilities and mathematical functions to explore datasets, identify patterns, and compute statistics. This is an essential part of data science and machine learning workflows, where NumPy acts as a foundational tool.

In [153]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

In [154]:
# Correlation Coefficient
print("Correlation Coefficient:\n", np.corrcoef(x,y))

Correlation Coefficient:
 [[1. 1.]
 [1. 1.]]


In [155]:
# Covariance
print("Covariance:\n",np.cov(x,y))

Covariance:
 [[  2.5  25. ]
 [ 25.  250. ]]


In [156]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [157]:
# Matrix Multiplication
product = np.dot(A, B)
print("Matrix Multiplication:\n", product)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [158]:
C = np.array([1, 2, np.nan, 4, np.nan, 6])
np.isnan(C)

array([False, False,  True, False,  True, False])

# Conclusion:
> The notebook provides a comprehensive overview of NumPy, focusing on its array manipulation capabilities and its use for various mathematical and statistical operations. It is a helpful guide for anyone looking to understand the basics and some advanced functionalities of NumPy. The examples cover a wide range of applications, demonstrating the versatility and power of NumPy in data science and numerical computing tasks.

#### Thank You